spring.application.name=candidature-dpss
# Port sur lequel ton serveur backend va tourner (8080 par défaut)
server.port=8080

# Ligne de connexion à MongoDB (va créer automatiquement la base de données)
spring.data.mongodb.uri=mongodb://localhost:27017/dpss_platform